### ISSUE TITLE
HTTPClient fails when Content-Length is not set

### ISSUE THREAD

**Issue by vi4m** [ZewoGraveyard/Development#12]
When HTTP response doesn't set Content-Length, http and https client raises and closedStream(0 bytes) error.
It should calculate total length read till the end of http server connection, when this header is not set.

How to reproduce? 

For this response:

```
HTTP/1.1 200 OK
Date: Fri, 16 Sep 2016 16:23:17 GMT
Connection: close

test
```

Run on the simplest http server (https://gist.github.com/vi4m/a3809caea5e4a59d27e1032f8b9657f1) 

And with this swift client code:

```

import HTTPClient

do {
    let c = try Client(url: "http://localhost:9000")
    let request = Request(method: .get, url: "/")
    var response = try c.request(request!)
}
catch {
    print(error)
    print("Failed.")
    exit(2)
}
print("Success.")

```

it will fail with closedStream(0 bytes error).

When the response is completed with "Content-Lenght: 5" http request works fine.

**Comment by paulofaria** [comment]
moved to https://github.com/Zewo/Zewo/issues/130
