### ISSUE TITLE
[HTTPClient] More flexibility with the default headers

### ISSUE THREAD

**Issue by 0xpablo** [ZewoGraveyard/Development#3]
I'm trying use the HTTPClient to connect to a server that requires me to sign the requests (including the headers). 
Since HTTPClient adds some default headers when it makes the request, I can't access them to include them into the signature.
It'd be great to expose them in some way.

Thanks!

**Comment by paulofaria** [comment]
@0xpablo hmm. you need to sign **all** headers?

**Comment by 0xpablo** [comment]
I'm afraid so :(
Look at the AWS documentation: http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

> Add the canonical headers, followed by a newline character. The canonical headers consist of a list of all the HTTP headers that you are including with the signed request.

**Comment by paulofaria** [comment]
moved to https://github.com/Zewo/Zewo/issues/138
